[package]
name = "binder"
authors = ["Android"]
version = "1.0.0"
edition = "2021"
rust-version = "1.67"

[dependencies]
downcast-rs = "1.2.0"
libc = "0.2.139"

binder_ndk_sys = { path = "../binder_ndk_sys" }
